import yuenler from '../images/headshots/yuenler.jpg';
import sarah from '../images/headshots/sarah.jpg';
import michael from '../images/headshots/MichaelBolgov.jpg';
import sudeep from '../images/headshots/SudeepC.jpg';
import allen from '../images/headshots/Allen.jpg';
import placeholder from '../images/headshots/Placeholder.jpg';
import kendree from '../images/headshots/kendreeC.jpg';
import devan from '../images/headshots/DevanAgrawal.png';
import vedi from '../images/headshots/vedi.jpg';
import maxwell from '../images/headshots/MaxwellYu.jpg';
import grace from '../images/headshots/GraceQiu.png';
import emmarose from '../images/headshots/emma.jpg';
import freya from '../images/headshots/FreyaShah.jpeg';
import vickie from '../images/headshots/VickieMao.jpg';
import bhavi from '../images/headshots/BhaviMood.jpg';
import tylina from '../images/headshots/tylina.jpg';
import sharon from '../images/headshots/SharonXiong.jpeg';
import dhyey from '../images/headshots/DhyeyShah.jpg';
import hana from '../images/headshots/HanaKaneko.jpg';
import jieling from '../images/headshots/JielingPua.jpg';
import millie from '../images/headshots/MillieHeredia.jpg';
import nathan from '../images/headshots/NathanKessler.png';
import ojaswinni from '../images/headshots/Ojaswinni.jpg';
import sanaaya from '../images/headshots/SanaayaHora.jpg';
import teddy from '../images/headshots/TeddyShi.png';
import rupinika from '../images/headshots/RupinikaGolla.jpg';
import sampreetha from '../images/headshots/Sampreetha.jpg';

const teamMembers = [
  {
    name: 'Michael Bolgov',
    school: 'University of Chicago',
    graduationYear: '‘27',
    profilePic: michael,
    role: 'Co-President',
    bio: "Michael is a second-year student at UChicago majoring in Molecular Engineering. He has been a gbSTEM math instructor, curriculum developer, and assistant director at gbSTEM prior to assuming his current role. Michael currently works as a research assistant intern at a lab affiliated with Harvard Medical School and Boston Children's Hospital studying possible treatments for Sickle Cell Disease. In his free time, Michael enjoys reading, playing  piano, acting, and playing tennis.",
    team: "presidents",
  },
  {
    name: 'Kendree Chen',
    school: 'Massachusetts Institute of Technology',
    graduationYear: '‘29',
    profilePic: kendree,
    role: 'Co-President',
    bio: 'Kendree is a freshman at MIT. She joined gbSTEM as a Scratch instructor and was CS director before becoming a president. She has taught coding classes for seven years, interned at a Boston University computer science lab, and works part-time as a freelance web developer. She founded the gbSTEM Lego Robotics program, and was captain of her high school FIRST robotics team. In her spare time, she enjoys crocheting, baking, and building websites with HTML, CSS, and JavaScript.',
    team: "presidents",
  },
  {
    name: 'Hana Kaneko',
    school: 'Boston University Academy',
    graduationYear: '‘27',
    profilePic: hana,
    role: 'Vice President',
    bio: 'Hana is a junior at Boston University Academy. She started at gbSTEM as a Scratch instructor and in-person LEGO robotics instructor and gained experience as a Communications Associate before becoming a Vice President. She is the lead of outreach and business of her school’s FIRST Robotics Competition (FRC) team, and has various experiences in one-on-one tutoring and mentoring in areas such as algebra, ELA, social studies, and time management. For fun, she likes playing soccer, sketching, and doing escape rooms.',
    team: "presidents",
  },
   {
    name: 'Jieling Pua',
    school: 'Brookline High School',
    graduationYear: '‘27',
    profilePic: jieling,
    role: 'Vice President',
    bio: 'Jieling is driven by a passion for STEM and education. She established and leads The SciSapience Club, engaging with professionals and showcasing student work to deepen understanding of scientific careers and opportunities. She has extensive experience in educational support, mentorship, and fostering welcoming communities for younger students, through roles as a math teaching assistant and tutor.',
    team: "presidents",
  },
  {
    name: 'Yuen Ler Chow',
    school: 'Harvard University',
    graduationYear: '‘25',
    profilePic: yuenler,
    role: 'Advisor',
    bio: "Yuen Ler is a senior at Harvard studying computer science and statistics. Yuen Ler founded gbSTEM in March of 2020 with the goal of increasing access to STEM education in his community.",
    team: "advisors",
  },
  {
    name: 'Sarah Meyer',
    school: 'Worcester Polytechnic Institute',
    graduationYear: '‘27',
    profilePic: sarah,
    role: 'Advisor',
    bio: "Sarah is a junior at WPI majoring in bioinformatics and computational biology. She started as a Scratch instructor during Spring 2021, and has been a part of the gbSTEM team ever since. She believes in making STEM education affordable and accessible for every family. Outside of gbSTEM, she enjoys coding, cooking, baking, and spending time with friends and family.",
    team: "advisors",
  },  
   {
    name: "Devan Agrawal",
    school: "Harvard University",
    graduationYear: "‘29",
    profilePic: devan,
    role: "Advisor",
    bio: "Devan is a freshman at Harvard University. He began learning Java in 4th grade and started instructing and TAing Java courses in 7th grade, which sparked his interest in teaching. At gbSTEM, Devan developed and taught the Python II course and Engineering III course and was Engineering Director before becoming vice president. In his free time, Devan likes to swim, play squash, do robotics, and play spirited card games with his family.",
    team: "advisors",
  },
  {
    name: 'Tylina Khamphavong',
    school: 'George Washington University',
    graduationYear: '‘29',
    profilePic: tylina,
    role: 'Advisor',
    bio: 'Tylina is a freshman at George Washington University. She joined gbSTEM as a math instructor in 2022 and has since then been an in-person instructor at the Cambridge Public Library teaching engineering. In school Tylina is captain of the Debate Team and is highly involved with Student Leadership. As well as being captain of her crew team, she loves running and staying active. She volunteers/works at her local Senior Home in the Memory Care unit. In her free time Tylina likes to read, listen to music, and hang out with friends.',
    team: "advisors",
  },
  {
    name: 'Vedi Raval',
    school: 'Harvard University',
    graduationYear: '‘29',
    profilePic: vedi,
    role: 'Outreach Director',
    bio: 'Vedi is passionate about computer science and economics. Since her childhood she has had a passion for STEM that she hopes to instill in others. Outside of gbSTEM, Vedi enjoys working out, listening to music, baking, and spending time with her friends and family!',
    team: "outreach & events",
  },
   {
    name: 'EmmaRose Zilla',
    school: 'Milton Academy',
    graduationYear: '‘26',
    profilePic: emmarose,
    role: 'Outreach Director',
    bio: 'EmmaRose is currently a senior at Milton Academy. She started working with gbSTEM in 2023 as a Math IV instructor and currently works as the partnership lead. EmmaRose is deeply passionate about STEM, particularly in the realm of chemistry, and plans to pursue a career in medicine. Outside gbSTEM, she is a competitive swimmer with a passion for reading, creative writing, and spending time with her friends and family.',
    team: "outreach & events",
  },
  {
    name: 'Luke Mussalli',
    school: '',
    graduationYear: '',
    profilePic: placeholder,
    role: 'Events Associate',
    bio: '',
    team: "outreach & events",
  },
  {
    name: 'Sampreetha Srimam',
    school: 'Sharon High School',
    graduationYear: '‘27',
    profilePic: sampreetha,
    role: 'Events Associate',
    bio: 'Sampreetha is a junior at Sharon High School. In her free time she loves to bake, read, and listen to music. She has a keen interest in STEM and has loved computer science ever since she was introduced to the coding language Python! As a second term events associate, she is looking forward to organizing more events!!',
    team: "outreach & events",
  },
  {
    name: 'Rupinika Golla',
    school: 'Milford High School',
    graduationYear: '‘28',
    profilePic: rupinika,
    role: 'Communications Associate',
    bio: 'Rupinika is a sophomore at Milford High School. She joined gbSTEM in 2025 as a math instructor and enjoys helping younger students develop confidence in problem solving. She is passionate about math and computer science and hopes to pursue a career in a STEM-related field. Outside of gbSTEM, Rupinika enjoys playing the guitar, violin, and tennis.',
    team: "outreach & events",
  },
   {
    name: 'Lukas Wellesley',
    school: '',
    graduationYear: '',
    profilePic: placeholder,
    role: 'Partnership Lead',
    bio: '',
    team: "outreach & events",
  },
  {
    name: 'Talia Hsieh',
    school: '',
    graduationYear: '',
    profilePic: placeholder,
    role: 'Partnership Lead',
    bio: '',
    team: "outreach & events",
  },
  {
    name: 'Allen Yu',
    school: 'Tufts University',
    graduationYear: '‘28',
    profilePic: allen,
    role: 'Math Co-Director',
    bio: 'Allen is a sophomore at Tufts University studying chemical engineering. He was a gbSTEM python instructor prior to assuming his current role. Outside of gbSTEM, he loves to write articles and short stories to be published online, play tennis, and listen to classical pieces, such as Nocturne, Op. 9 No. 2 by Frédéric Chopin.',
    team: "math",
  },
  {
    name: 'Sudeep Chitrothu',
    school: 'Northwestern University',
    graduationYear: '‘28',
    profilePic: sudeep,
    role: 'Math Co-Director',
    bio: 'Sudeep is a sophomore at Northwestern University. Last fall he was an instructor at gbSTEM. He enjoys teaching, problem-solving, and research. His hobbies include preparing for math competitions such as the AIME, coding, and studying for science olympiad.',
    team: "math",
  },
  {
    name: 'Leila Koplan',
    school: '',
    graduationYear: '',
    profilePic: placeholder,
    role: 'Math I Curriculum Developer',
    bio: "",
    team: "math",
  },
  {
    name: 'Zac Lipchin',
    school: '',
    graduationYear: '',
    profilePic: placeholder,
    role: 'Math II Curriculum Developer',
    bio: "",
    team: "math",
  },
  {
    name: 'Dhyey Shah',
    school: 'Chelmsford High',
    graduationYear: '‘28',
    profilePic: dhyey,
    role: 'Math III Curriculum Developer',
    bio: "Dhyey is a math educator with a background in teaching Mathematics II, now leading the Math III team. He enjoys blending logic with strategy—whether in teaching or playing soccer, cricket, or chess. He is also a member of his school's math and science teams, where he continues to explore new challenges and collaborate with peers who share his enthusiasm for STEM.",
    team: "math",
  },
  {
    name: 'Vickie Mao',
    school: 'Milton Academy',
    graduationYear: '‘25',
    profilePic: vickie,
    role: 'Math IV Curriculum Developer',
    bio: 'Vickie is currently a junior at Milton Academy. She has had a passion for math and science since she was young and has joined gbSTEM in 2024 as a math instructor. Currently, she is working as a math IV curriculum developer through which she wishes to share her excitement for problem solving. Outside of gbSTEM, she enjoys reading, playing volleyball and spending time in nature.',
    team: "math",
  },
  {
    name: 'Nathan Kessler',
    school: 'Newton North High School',
    graduationYear: '‘26',
    profilePic: nathan,
    role: 'Math V Curriculum Developer',
    bio: ' Nathan is a senior at Newton North High School and joined gbSTEM in 2024 as a CS and later math instructor. He enjoys math competitions and is excited for creating lessons for Math V. He enjoys reading, working out, and eating in his free time.',
    team: "math",
  },
  {
    name: 'Maxwell Yu',
    school: 'California Institute of Technology',
    graduationYear: '‘29',
    profilePic: maxwell,
    role: 'Computer Science Director and Web Curriculum Developer',
    bio: 'Maxwell joined gbSTEM in 2022 as a web development instructor. He first started teaching himself to code when he was six years old and is now experienced with HTML/CSS/JS, Java, C#, C++, Python, Powershell, and R. He maintains multiple professional websites, including that of his robotics team. He has also reached the silver division of the USA Computing Olympiad and worked as a data science intern at a neurobiology lab. He is eager to share his passion for coding, encouraging students to explore computer science independently and think critically to solve problems.',
    team: "computer science",
  },
  {
    name: "Teddy Shi",
    school: "Boston University Academy",
    graduationYear: "‘27",
    profilePic: teddy,
    role: "Scratch I Curriculum Developer",
    bio: "Teddy is a junior at Boston University Academy. He first began working at gbSTEM in 2024. He has experience teaching students of many ages. In his free time, he enjoys playing volleyball, doing photography and participating in his school robotics team. Teddy is excited to work with everyone in the upcoming semester!",
    team: "computer science",
  },
  {
    name: "Freya Shah",
    school: "Chelmsford High School",
    graduationYear: "‘26",
    profilePic: freya,
    role: "Scratch II Curriculum Developer",
    bio: "Freya is a senior at Chelmsford High School. She taught Scratch for gbSTEM in the spring semester of 2024. She started learning how to code a few year ago, but dove deeper into Python recently. She has enjoyed taking math and science classes, taking Russian Math classes outside of school. She is an avid member in her school's science, math, robotics, and speech and debate team. Outside of school, she enjoys singing, playing the guitar, and hanging out with friends.",
    team: "computer science",
  },
  {
    name: "Shaun Ng",
    school: "Boston University Academy",
    graduationYear: "‘27",
    profilePic: placeholder,
    role: "Python I Curriculum Developer",
    bio: "",
    team: "computer science",
  },
  {
    name: "Dillan Agrawal",
    school: "",
    graduationYear: "",
    profilePic: placeholder,
    role: "Python II Curriculum Developer",
    bio: "",
    team: "computer science",
  },
  {
    name: "Grace Qiu",
    school: "Mass Academy",
    graduationYear: "‘26",
    profilePic: grace,
    role: "Engineering Co-Director",
    bio: "Grace is a senior at Mass Academy. She first began working at gbSTEM in 2022 as an Engineering I instructor. She has experience teaching students of all ages and wants to work in the STEM field. Her favorite hobbies are swimming, art, and music. Grace is excited to become the engineering director this year, and looks forward to working with everyone!",
    team: "engineering",
  },
  {
    name: 'Bhavi Mood',
    school: "North Attleboro High School",
    graduationYear: "‘26",
    profilePic: bhavi,
    role: "Engineering Co-Director and Engineering III Developer",
    bio: "Bhavi is a senior at North Attleboro High School. He is the current Engineering Co-Director and Engineering III developer for gbSTEM and was previously an Engineering I instructor. Additionally, Bhavi is a varsity tennis player, student representative to the North Attleboro School Committee, and co-founder of the NASTP Digital Literacy volunteer initiative.",
    team: "engineering",
  },
  {
    name: "Ojaswinni Upadhyay",
    school: "",
    graduationYear: "‘26",
    profilePic: ojaswinni,
    role: "Engineering I In-Person Curriculum Developer",
    bio: "Ojaswinni is a senior attending Lexington High School. She is currently the Engineering 1 curriculum developer for both the online and in-person course. Some of her favorite subjects are math, physics, and astronomy. She loves going for night drives with her friends and observing the stars!",
    team: "engineering",
  },
  {
    name: "Saanaya Hora",
    school: "Nobles and Greenough School",
    graduationYear: "‘28",
    profilePic: sanaaya,
    role: "Engineering I Curriculum Developer",
    bio: "Sanaaya is a sophomore at the Noble and Greenough School where her favorite classes are math and art. She joined gbSTEM as an engineering instructor and now is an engineering curriculum developer. Sanaaya has participated in First Lego League and VEX robotics competitions, and takes advanced math classes through the Russian School of Math. Outside of school, she loves to bake, read, and play basketball with her little brother.",
    team: "engineering",
  },
  {
    name: "Aarav Gupta",
    school: "",
    graduationYear: "‘",
    profilePic: placeholder,
    role: "Engineering III Curriculum Developer",
    bio: "",
    team: "engineering",
  },
   {
    name: "Aarav Agrawal",
    school: "",
    graduationYear: "‘",
    profilePic: placeholder,
    role: "Engineering III Curriculum Developer",
    bio: "",
    team: "engineering",
  },
  {
    name: 'Millie Heredia',
    school: 'Milton Academy',
    graduationYear: '‘27',
    profilePic: millie,
    role: 'Environmental Science Curriculum Developer',
    bio: 'Millie is a junior at Milton Academy. She has previously been an Environmental Science instructor at gbSTEM and is now an Environmental Science curriculum developer. She enjoys playing on the varsity volleyball team, baking, and hanging out with friends and roommates',
    team: "science",
  },
  {
    name: "Sharon Xiong",
    school: "Boston University Academy",
    graduationYear: "‘27",
    profilePic: sharon,
    role: "Physics Curriculum Developer",
    bio: "Sharon is a junior at Boston University Academy with a strong interest in physics and engineering. She joined gbSTEM as an instructor for the in-person LEGO robotics program and is currently helping develop a new physics curriculum after taking two physics courses at Boston University. Outside the classroom, Sharon is a tour guide at her school and an active member of the FIRST Robotics Competition team. In her free time, she enjoys exploring Boston with friends, playing soccer, and tennis.",
    team: "science",
  }
];

export default teamMembers;
